<template>
	<body>
		<header class="mui-bar mui-bar-nav">
			
			<h1  style="color:white" class="mui-title">Settings</h1>
		</header>
		<nav class="mui-bar mui-bar-tab">
			<router-link to="/schedule" class="mui-tab-item">
				<span class="mui-icon mui-icon-home"></span>
				<span class="mui-tab-label">Schedule</span>
			</router-link>
			<router-link to="/order" class="mui-tab-item">
				<span class="mui-icon mui-icon-list"></span>
				<span class="mui-tab-label">Orders</span>
			</router-link>
			<router-link to="/summary" class="mui-tab-item">
				<span class="mui-icon mui-icon-flag"></span>
				<span class="mui-tab-label">Summary</span>
			</router-link>
			<router-link to="/setting" class="mui-tab-item mui-active">
				<span class="mui-icon mui-icon-gear"></span>
				<span class="mui-tab-label">Settings</span>
			</router-link>
		</nav>
    <mt-popup v-model="aboutUs" position="right" class="mint-popup-3" :modal="false">
			<header class="mui-bar mui-bar-nav">
				<a class="mui-icon mui-icon-close mui-pull-right"  @click="aboutUs = false"></a>
				<h1 style="color:white" class="mui-title">About Wii</h1>
			</header>
			<div class="mui-content" style="text-align:left;padding:10px;overflow-y:auto">
							<div style="    margin-top: 20px;">
					<p style="line-height: 1.2; margin-top: 15pt; margin-bottom: 7.5pt;"><strong><span style="font-size: 18px; font-family: Arial; color: #333333; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">One stop Home Services Platform</span></strong></p>

									<p>We have over 200 trained and experienced home services assistants in the lower Mainland who have been certified by our training system with training details listed under &ldquo;WiiCleaner&rdquo;.</p>
									<p>This platform saves you time from posting hiring ads to find the right home services assistant in the shortest period of time. WiiCleaner is an equal opportunity platform which created channels and flexibilities for all individuals who are interested in becoming a work professional again while not intervening with personal routine.</p>
									<p>WiiCleaner provides best services with upfront pricing. We are professional and confidence guaranteed.</p>
								</div>
			</div>
    </mt-popup>

    <mt-popup v-model="ToS" position="right" class="mint-popup-3" :modal="false">
			<header class="mui-bar mui-bar-nav">
				<a class="mui-icon mui-icon-close mui-pull-right"  @click="ToS = false"></a>
				<h1 style="color:white" class="mui-title">Terms of Service</h1>
			</header>


			<div class="mui-content" style="text-align:left;padding:10px;overflow-y:auto">
						<p style="line-height: 1.2; margin-top: 15pt; margin-bottom: 7.5pt;"><strong><span style="font-size: 18px; font-family: Arial; color: #333333; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TERMS AND CONDITIONS OF USE</span></strong></p>
						<ol>
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 15px; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> DEFINITIONS AND INTERPRETATION</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.1 In this Agreement, unless the context otherwise requires:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"One Time Service"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means an ad hoc Session that a Customer has booked;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Booking"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means to the submission of a request to the Platform for a Service Provider;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Cancellation Fee"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the charge incurred and payable to WiiCleaner when a Customer or Service Provider cancels or makes changes to a Session or Recurring ;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Code"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the discount or promotional code WiiCleaner offers that a Customer may input into the Platform to obtain certain determined benefit;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Odd Hours Allowance"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the additional charge incurred by a Customer when the Session is between 6pm to 8am;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Recurring Service"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the series of Sessions for a duration that a Customer is able to book or has booked through the Platform;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Payment Gateway"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the payment service provider WiiCleaner uses for all transactions via its Platform;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Platform"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the Website and App;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Service Provider"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the person that has accepted the Recurring Service or Session booked by a Customer;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Session"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means the scheduled event a Customer has booked through the Platform;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Website"</span></strong></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">means the domain http://wiicleaner.ca/, its subdomains and webpages;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"You"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,&nbsp;</span><strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"your"</span></strong><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;means you as the user of the Platform.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1.2 In this Agreement, unless the context otherwise requires:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) where a word or expression is defined, other parts of speech and grammatical forms of that word or expression, and cognate expressions, have corresponding meanings;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) the use of the word "including" is not a word of limitation;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(c) a reference to the singular or plural can also refer to the other;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(d) headings are for visual purposes and shall not affect interpretation or construction;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(e) a reference to an Act of Parliament, in part or in whole, includes any amendment, consolidation, modification, re-enactment or reprint of the referred Act of Parliament, in part or in whole, or any Act of Parliament that replaces it;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(f) a reference to a document includes all amendments or supplements to, or replacements or novations of, that document;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(g) all monetary amounts are in Canada dollars;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(h) all time references are in Vancouver local time.</span></p>
						<ol start="2">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> OVERVIEW</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.1 Fore Services Ltd ("WiiCleaner ") operates and manages the Platform through which a user (the "Customer") can book a session for the service categories WiiCleaner offers. The confirmation of a Service Provider to the recurring service or session constitutes a successful booking.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.2 WiiCleaner is not an agent or broker, but merely serves the role as the operator of its Platform to facilitate the booking of Sessions of the Customer with a Service Provider.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.3 These Terms and Conditions of Use (the "T&amp;C"), including the Privacy Policy (collectively the "Agreements"), governs the access and use of the Website and App. By using WiiCleaner Platform, you agree to be bound by these Agreements stated herein. If you do not agree to these conditions, please discontinue your access immediately.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2.4 WiiCleaner periodically reviews and reserves the right to make changes to the Agreements without any notice to the Customer. While WiiCleaner may at its discretion provide notice for any changes, the Customer should review these documents regularly as such changes are of immediate effect from the date of update to the Agreements. Your continued use of the Platform shall constitute your acceptance of such changes.</span></p>
						<ol start="3">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> THIRD PARTY PRODUCTS AND SERVICES</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Any third party applications, websites, products, and services ("Third Party Products and Services") linked with the usage of WiiCleaner Platform have their own terms and conditions and privacy policies, and your use of these Third Party Products and Services are governed by such agreements. WiiCleaner is not responsible or accountable for anything that occurs with your usage of Third Party Products and Services.</span></p>
						<ol start="4">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> LIABILITY AND WARRANTY</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.1 WiiCleaner shall not be liable in contract or in tort for any loss or damage suffered and consumer rights are limited to those set out in this T&amp;C and under statute.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.2 The Customer further agrees that to the extent permitted by law WiiCleaner shall not be liable to the Customer for a) any incidental, indirect, special or consequential damages, b) loss of opportunity, c) loss of revenue, d) loss of profit or anticipated profit, e) loss of business f) loss of contracts, g) loss of goodwill, h) loss arising out of business interruption, i) loss arising out of or in connection with pollution or contamination, all arising out of or in connection with the purchase, use or performance of products or services, even if WiiCleaner has been advised of their possibility.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.3 To the extent permitted by law and the Agreements, WiiCleaner total liability herein in respect of each event or series of connected events shall not exceed the service price paid by Customer for the applicable service.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.4 In the absence of specific instructions from the Customer to omit or perform certain actions in a certain way, the Service Provider shall perform the tasks assigned according to their own discretion, and the Customer cannot hold WiiCleaner nor the Service Provider liable for any loss or damage as a result of such absence of specific instructions.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.5 Force Majeure: Neither party shall be liable for any delay in performing any of its obligations under this T&amp;C if such delay is caused by circumstances beyond the reasonable control of the party so delaying, and such party shall be entitled to a reasonable extension of time for the performance of such obligations.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.6 Any breach of the T&amp;C by either the Customer and Service Provider will result in the party in breach remaining liable to the affected party who shall retain all remedies and rights available to them.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.7 The information and materials contained in the Platform and all sites linked to the Platform, including text, graphics, links, or other items are provided "as is" and "as available". WiiCleaner and its affiliates, directors, officers, employees, agents, contributors, third party content providers or licensors does not warrant the accuracy, adequacy, reliability or completeness of this information and materials and expressly disclaims liability for errors or omissions in such information and materials.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.8 No warranty of any kind, implied, express or statutory, including but not limited to the warranties of noninfringement of third party rights, title, merchantability, satisfactory quality, fitness for a particular purpose and freedom from computer virus, is given in conjunction with the information and materials. This disclaimer shall take effect to the fullest extent permitted by law.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4.9 Any typographical, clerical or other error or omission in service literature, quotation, price list, acceptance of offer, invoice or other documents or information issued by WiiCleaner shall to the extent permitted by law be subject to correction without any liability on the part of WiiCleaner.</span></p>
						<ol start="5">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> COPYRIGHT AND INTELLECTUAL PROPERTY</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5.1 The copyright in this website is owned by WiiCleaner. No part or parts hereof may be reproduced, distributed, republished, displayed, broadcast, hyperlinked or transmitted in any manner or by any means or stored in an information retrieval system without the prior written permission of WiiCleaner or the copyright owner:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) provided that permission is granted to download and print the materials on this website for personal, non-commercial use only;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) provided you do not modify the materials and that you retain all copyright and other proprietary notices contained in the materials. This permission terminates automatically if you breach any of these terms or conditions. Upon termination, you will immediately destroy any downloaded and printed materials. You also may not, without WiiCleaner permission, "mirror" any material contained on this website on any other server.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5.2 The trademarks, service marks, and logos (the "Trademarks") used and displayed on this website are registered and unregistered Trademarks of WiiCleaner and others. Nothing on this website should be construed as granting, by implication, estoppels, or otherwise, any license or right to use any Trademark displayed on this website, without the written permission of WiiCleaner or other Trademark owner.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">5.3 WiiCleaner aggressively enforces its intellectual property rights to the fullest extent of the law. The name of WiiCleaner or the WiiCleaner logo may not be used in any way, including in advertising or publicity pertaining to distribution of materials on this website, without prior written permission. WiiCleaner prohibits use of the WiiCleaner logo as a "hot" link to any WiiCleaner site unless establishment of such a link is approved in advance by WiiCleaner in writing.</span></p>
						<ol start="6">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> MARKETING CAMPAIGNS</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.1 From time to time, WiiCleaner through its Platform or other channels including partners, publications, and social media, may conduct campaigns in the form of promotions, codes, discounts, contests, giveaways, and offers ("Campaign"). These Campaigns are governed by additional terms and conditions and you agree to be governed by such terms and conditions.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">6.2 WiiCleaner reserves the right, in its absolute discretion, to determine your eligibility for a Campaign, and, subject to applicable laws, to withdraw or to modify a Campaign at any time without prior notice and without liability, to the greatest extent permitted under the law.</span></p>
						<ol start="7">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> INDEPENDENT CONTRACTORS</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Service Providers under the WiiCleaner Platform are engaged by the Customer as an independent contractor. Nothing in this Agreement shall be construed as creating a partnership, joint venture or employer-employee relationship between the parties. Neither party, Service Provider nor WiiCleaner, is the agent of the other and no party is authorised to make any representation, contract or commitment on behalf of the other party without express consent from the other.</span></p>
						<ol start="8">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> SUPPORT</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">8.1 In respect of the Platform, WiiCleaner will provide general customer service and support to the Customer in accordance with the then-current service and support policies in effect as stated in contract.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">8.2 Service and support offerings may vary from service to service and WiiCleaner makes no guarantees or warranties of any kind that WiiCleaner will answer any queries within any timeframe, even if stated otherwise during correspondence, or satisfactorily answer such queries despite WiiCleaner best endeavours to do so.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">8.3 WiiCleaner has no obligation to provide service or support until WiiCleaner has received full payment for the service/support contract purchased by the Customer. WiiCleaner is not obligated to provide third-party branded service or support (including telephone support).</span></p>
						<ol start="9">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> BOOKINGS AND SERVICES</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 15pt; margin-bottom: 7.5pt;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.1 General</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.1.1 The Customer agree that all information provided in the Booking is as accurate as possible, that the Service Provider have all rights to reject any tasks listed in the Booking, and that WiiCleaner may terminate the Session or Recurring Service at its discretion should any of the information in the Booking be found to be inaccurate. The Customer will be liable for charges incurred if the Session or Recurring Service is cancelled at any time or reason as a result of inaccurate information in their Booking according to the schedule in section 11.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.1.2 The tasks assigned are not guaranteed to be completed within the duration; extension of the duration of a Session ("Additional Hours") might be required and charged accordingly. In such a case, the Service Provider has the right to reject the Additional Hours. Should the Service Provider accept, Additional Hours will be not deducted from the remaining hours in the Recurring Service but will be counted outside of the Recurring Service.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.1.3 Should a Service Provider cancel a Session for whatever reason, and the Platform be unable to find a replacement Service Provider 24 hours before the start of the next Session, the Customer may elect to change the Booking or cancel the Session free of charge.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.1.4 WiiCleaner does not guarantee the same Service Provider for a Customer for all Sessions booked by the Customer.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.1.5 The Service Provider has the right to reject any task that is deemed to be illegal or a health or life risk. To avoid potential harm, the Service Provider can reject the lifting of any furniture, appliances, decor, and other items to clean an area. The Customer is required to do this before the Session. If the Customer decides to proceed otherwise and the Service Provider is agreeable, the Service Provider shall not be liable for any damages done to the property of the Customer.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.1.6 The Service Provider has the right to reject an instruction to perform a task in a certain way when a better or easier way can be done. The Service Provider will not mop the floor using their hands and cloth nor will they hand wash clothes no matter the reason. They however, can mop the floor with a mop and use the washing machine.</span></p>
						<p style="line-height: 1.2; margin-top: 15pt; margin-bottom: 7.5pt;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.2 Home Cleaning</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.2.1 Customer, is required to supply their own cleaning equipment, materials &amp; solutions to the Service Provider for the chosen service. The quality and result of the cleaning service is dependent on what was supplied to the Service Provider for the chosen service.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.2.2 Customers, may request the Service Provider to assist in purchasing any required equipment, material or solutions to perform the chosen service. Reimbursement of the requested purchase is a separate charge to the rates of the service, and has to be paid to the Service Provider.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.2.3 Should laundry washing service be required, Service Provider should only complete the chosen service by using washing machine and not manual hand wash.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.2.4 Minimum hours per session is 3 hours.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.2.5 The Service Provider shall only perform the job scope specified in the WiiCleaner platform. The Service Provider have all rights to reject any tasks that are not included in the job scope.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.2.6 Any household items, appliances or fixtures that require dismantling for cleaning, will have to be done by the Customers themselves. The Service Provider shall not perform such dismantling tasks. Failure on the part of the Customers to perform this task prior to the beginning of the job session, the Service Provider shall not clean the items.</span></p>
						<p style="line-height: 1.2; margin-top: 15pt; margin-bottom: 7.5pt;"><span style="font-size: 18pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.3 Move-in/out Cleaning</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.3.1 Customer, is required to supply their own cleaning equipment, materials &amp; solutions to the Service Provider for the chosen service. The quality and result of the cleaning service is dependent on what was supplied to the Service Provider for the chosen service.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.3.2 Customers, may request the Service Provider to assist in purchasing any required equipment, material or solutions to perform the chosen service. Reimbursement of the requested purchase is a separate charge to the rates of the service, and has to be paid to the Service Provider.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.3.3 The Service Provider shall only perform the job scope specified in the WiiCleaner platform. The Service Provider have all rights to reject any tasks that are not included in the job scope. Move-in/out cleaning or spring cleaning is a deep cleaning job. Customer should not book home cleaning for a move-in/out cleaning service.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.3.4 Minimum hours per session is 4 hours.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.3.5 The Service Provider shall only perform the job scope specified in the WiiCleaner platform. The Service Provider have all rights to reject any tasks that are not included in the job scope.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">9.3.6 Any household items, appliances or fixtures that require dismantling for cleaning, will have to be done by the Customers themselves. The Service Provider shall not perform such dismantling tasks. Failure on the part of the Customers to perform this task prior to the the beginning of the job session, the Service Provider shall not clean the items.</span></p>
						<ol start="10">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> PAYMENT</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10.1 The Customer shall make all payments through the Platform, which in turn uses a Payment Gateway to process such payments, unless agreed upon by WiiCleaner in writing for alternative methods. The cash payment is not permitted, except for grocery shopping or tips. Alternative payment methods can be discussed and must be agreed upon by WiiCleaner before the performance of the service.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10.2 The Customer agrees that the Payment Gateway will process the validity of the credit card through an authorisation charge equal to the Session fee one day prior to the Session, the amount only fully deducted from the credit card upon completion of the Session.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10.3 Should the credit card be declined by the Payment Gateway during an authorisation charge, and a valid credit card not be keyed into the Platform and authorised, WiiCleaner shall cancel the Session.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10.4 Additional charges to the Session may apply according to certain conditions listed in the Platform, including but limited to Travel Allowance and Odd Hours Allowance, or during public holidays, their eves, and other peak periods at the discretion&nbsp;of WiiCleaner.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10.5 The Customer and Service Provider recognises that WiiCleaner provides value in money and time as an intermediary to both parties. As such, any action that encourages or solicits complete or partial payment, of the services engaged, outside of the Platform is a violation of the T&amp;C. The party in breach is liable to compensate WiiCleaner for damages of a monetary amount determined by WiiCleaner, and access to the Platform will be suspended.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10.6 Parties who report violations of clause 10.5 shall be rewarded by WiiCleaner accordingly.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">10.7 WiiCleaner shall pay weekly the Service Provider for their services performed for that cycle.</span></p>
						<ol start="11">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> CHANGES AND CANCELLATIONS</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">11.1 For all Recurring Services except a One Time Service, the Customer and Service Provider may cancel or make changes to a Session free of charge up to 48 hours before the Session, after which, unless provided by clause 9.3:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) the Customer will be charged for the full Session if the Customer cancels or makes changes to the Session within 24 hours before the start of the Session.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) the Customer will be charged for an hour if the Customer cancels the Session within 48 hours before the start of the Session.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">11.2 When a Customer books a One Time Service, unless provided by clause 9.3:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) the Customer will be charged for the full Session if the Customer cancels or makes changes to the Session within 24 hours before the start of the Session.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) the Customer will be charged for an hour if the Customer cancels the Session within 48 hours before the start of the Session.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">11.3 A Cancellation Fee of $50 will be incurred when the Customer cancels the Recurring Service or when the Recurring Service expires.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">11.4 In the event that a Service Provider reached the location of the Session, and the Customer is not there to let the Service Provider in and cannot be reached. The Service Provider can leave the location and the Session will be treated as cancelled. The Service Provider shall take a photo of themselves in the location as proof.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">11.5 Notwithstanding clause 11.1 and 11.2, if the Customer delays the start of the Session within the time frame of 1 hour on the day itself, the Service Provider may leave at the original scheduled time and the Session shall be treated as completed. Should the Customer elect to extend the session with the agreement of the Service Provider, such an extension shall be treated as Additional Hours as per clause 9.3.</span></p>
						<ol start="12">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> REFUNDS, WAIVERS AND CLAIMS</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">12.1 Any refund or waiver of any charge is issued by WiiCleaner at its own discretion and does not commit WiiCleaner to any future refund or waiver of any charge. WiiCleaner reserves the right to judge the validity of cause of evidence for a refund or waiver of any charge.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">12.2 WiiCleaner Guarantee Program - provides certain limited additional protections. Pursuant to the WiiCleaner Guarantee Program and subject to the below terms and conditions and limitations, WiiCleaner will compensate the Customer:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) subject to the exclusions below, up to CAD $300 per occurrence for losses arising from property damage as a direct result of negligence of a Service Provider during performance of a Session;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) provided, however, for losses arising from damage to floors as a direct result of negligence of a Service Provider during performance of a Session the amount shall be limited to up to CAD $100;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(c) subject to the exclusions below, Customers up to CAD $300 for losses arising from theft of a Customer&rsquo;s property by a Service Provider during performance of a Session. The Customer is eligible for the WiiCleaner Guarantee Program provided that the Customer reports the issue within forty-eight (48) hours of the Session to our Customer service by emailing us at sg@helpergo.co. If the Customer does not report the issue within forty-eight (48) hours of the Session, the claim is ineligible for the WiiCleaner Guarantee Program. For Recurring Service Session, each Session is treated as a separate occurrence.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">12.3 If Customer carry insurance that would cover the Customer in the event of a claim, such as renter&rsquo;s insurance, homeowner&rsquo;s insurance, automobile insurance or any other personal insurance, Customer agree that the personal insurance is primary and the WiiCleaner Guarantee Program is secondary. The WiiCleaner Guarantee Program will only compensate for losses to the extent not otherwise covered by Customer's personal insurance and only as permitted herein.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">12.4 Customer will be covered under the WiiCleaner Guarantee Program for every Session, subject to the exclusions below, provided:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) The Session is agreed to between a Customer and a Service Provider using the WiiCleaner Platform, performed by the Service Provider hired by the Customer and paid for in full through the WiiCleaner Platform;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) The Customer has not violated this Agreement;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(c) The Customer has reported the claim within 48 hours of the Session; and</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(d) Your WiiCleaner account is in good standing with no outstanding balances owed to WiiCleaner or Service Providers.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">12.5 What is excluded from the WiiCleaner Guarantee Program? The WiiCleaner Guarantee Program&rdquo; does not cover the following:</span></p>
						<ul style="margin-top: 0pt; margin-bottom: 0pt;">
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising out of acts of nature, including, but not limited to, pollution, earthquakes and weather related events such as hurricanes and tornadoes;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising out of interruption of business, loss of market, loss of income and/or loss of use;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses for property damage and theft exceeding the original value and/or replacement value for such property, less any standard depreciation;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising from negligencethe acts or omissions of a Customer or third party;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising from a manufacturer&rsquo;s or a product&rsquo;s defects;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses from pre-existing damages or conditions of the item or property;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising from items supplied by the Customer or due to Requester recommendations (e.g., if a manufacturer recommends affixing furniture to a wall and a Requester declines to have furniture affixed, etc);</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising from flooding and/or water damage including mold, fungi or bacteria;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising from products containing hazardous or harmful materials, acts of terrorism, product liability, or pollution;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses of cash, third party gift cards, and securities;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses as a result of an intentional wrongful act by a Service Provider;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising from normal wear and tear;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses for items that retain their functionality; (e.g., minor cosmetic damage, ordinary wear and tear, a t.v. that has a scratch on the bezel);</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses for fine arts, which includes but is not limited to paintings, etchings, printed photos, pictures, tapestries, rare or art glass, art glass windows, valuable rugs, statuary, sculptures, antique furniture, antique jewelry, bric-a-brac, porcelains, antique automobiles, coins, stamps, other collectibles, collections, furs, jewelry, precious stones, precious metals, and similar property of rarity, historical value;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses for damage beyond the specific damaged area (e.g., should flooring sustain damage, any loss is limited to the replacement cost of the square footage that was damaged after deducting for obsolescence and physical depreciation); loss of use damages, including without limitation, loss of use such as property, furniture and the costs of any storage, movement and insurance of furniture in connection with loss of use;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses excluded pursuant to Section 4 of the Agreement;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses based on sentimental and/or undocumented intangible value;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses or damages associated with the unauthorized acquisition of, access to, destruction of, and/or loss of electronic data, including but not limited to films, records, manuscripts, drawings or photographs, data, information, audio or video recordings, files, facts, programs or other materials stored as or on, created or used on, or transmitted to or from, computer software, including systems and applications software, hard or floppy disks, CD-ROMs, tapes, drives, cells, data processing devices, cloud storage, or any other media which are used with electronically-controlled equipment;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses related to repairs outside of the area where the Sessions were performed;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses of pets, personal liability or damage to shared or common areas;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses arising from shipping costs and/or shipping of replacement items and/or taxes incurred in purchasing the original and/or replacement items;</span></li>
						<li style="list-style-type: disc; font-size: 10pt; font-family: Verdana; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">losses of theft without a valid police report, if requested by WiiCleaner; and losses with insufficient documentation.</span></li>
						</ul>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">12.6 How do I submit a Claim?</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) First report of a claim must be made within 48 hours after the Session occurs. After the first report, you will be asked to complete the full claim form within 7 days of receipt. We urge you to read through these terms and conditions prior to submitting a claim. All claims will be reviewed on a case-by-case basis. During WiiCleaner claims assessment process, you may be required to provide written detailed: (i) proof of ownership of damaged/missing item; (ii) proof of value of damaged/missing item; and (iii) proof of damage or loss. If such information is requested, you will have 30 days from the date of the request to send WiiCleaner the requested information. If you fail to provide the requested information within the 30 day time period and/or fail to contact WiiCleaner to arrange for an extension of time, Your claim will be considered closed. You also agree to: (i) protect and preserve any damaged property that is the basis of a claim from further damage, (ii) assist and allow WiiCleaner or its insurers access to inspect and make copies, photographs and recordings of anything relating to the claim, (iii) accept repairs and/or remediation by a Service Provider, (iv) accept a replacement only if repairs are proven not to be an option, (v) submit requested materials by the dates outlined by the WiiCleaner resolutions team,; and (vi) accept a replacement item subject to the standard depreciation of that item.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) If any part of Your claim is approved, then as a condition to any payment to You under the WiiCleaner Guarantee Program, You will be required to execute and deliver to WiiCleaner the release agreement within 14 days of receipt of the release agreement from WiiCleaner, and assign to WiiCleaner or its insurer any rights and remedies you may have to recover amounts paid to you with respect to an approved claim from any party that is financially responsible for the approve claims and any rights in any property that is recovered. The release agreement shall be rescinded and considered null and void if not signed and returned to WiiCleaner within 14 days of Your receipt and the claim shall no longer shall be eligible for the WiiCleaner Guarantee Program.</span></p>
						<ol start="13">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> TERM AND TERMINATION</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">13.1 The terms of this TOS are valid upon the successful booking of a Session or Recurring Service and will terminate upon:</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(a) a material breach of the Agreements by either party, whereby the affected party shall terminate the TOS on written notice to the other party;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(b) the cancellation of a Session or Recurring Service either by the Customer or Service Provider and that all parties have fulfilled their obligations under the T&amp;C;</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(c) the completion of a Session or Recurring Service and that all parties have fulfilled their obligations under the T&amp;C.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">13.2 Notwithstanding clause 13.1, WiiCleaner reserves the right to (a) modify or discontinue, temporarily or permanently, the Platform; (b) refuse any and all current and future use of the Platform and suspend or terminate the Customer's&nbsp;account for any reason. WiiCleaner will in its best endeavours warn the Customer of any such action..</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">13.3 In the event that WiiCleaner terminates the Agreements or suspend a Customer's access to the Platform, WiiCleaner shall have no liability or responsibility to the Customer and no refunds of any amount paid will be made, to the fullest extent under applicable law.</span></p>
						<ol start="14">
						<li style="line-height: 1.2; margin-top: 15pt; margin-bottom: 11.25pt;"><span style="font-size: 21pt; font-family: Arial; color: #333333; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> GENERAL PROVISIONS</span></li>
						</ol>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">14.1 If any provision of this T&amp;C is held by any competent authority to be invalid or unenforceable in whole or in part, the validity of the other provisions of these Terms and Conditions and the remainder of the provisions in question shall not be affected thereby.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">14.2 Save as expressly provided herein, any term of this T&amp;C shall not be enforceable under the Contracts (Rights of Third Parties) Act 1999 by a third party.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">14.3 No forbearance, delay or indulgence on WiiCleaner part in exercising any power or right under this T&amp;C shall prejudice or restrict the rights of WiiCleaner, nor shall any waiver of its rights operate as a waiver of any subsequent breach, and no right, power or remedy herein conferred upon or reserved for either party, is exclusive of any other right, power or remedy available to that party and each such right, power or remedy shall be cumulative.</span></p>
						<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 11.25pt;"><span style="font-size: 12pt; font-family: Arial; color: #777777; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">14.4 This T&amp;C shall be governed by and construed in accordance with the laws of Canada and shall be subject to the non-exclusive jurisdiction of the courts of Canada.</span></p>
						<p style="line-height: 1.2; margin-top: 15pt; margin-bottom: 7.5pt;"><br /><br /></p>
			</div>
    </mt-popup>

    <mt-popup v-model="FAQ" position="right" class="mint-popup-3" :modal="false">
			<header class="mui-bar mui-bar-nav">
				<a class="mui-icon mui-icon-close mui-pull-right"  @click="FAQ = false"></a>
				<h1 style="color:white" class="mui-title">FAQ</h1>
			</header>


			<div class="mui-content" style="text-align:left;padding:10px;overflow-y:auto">
				faq
			</div>
    </mt-popup>

    <mt-popup v-model="contactUs" position="right" class="mint-popup-3" :modal="false">
			<header class="mui-bar mui-bar-nav">
				<a class="mui-icon mui-icon-close mui-pull-right"  @click="contactUs = false"></a>
				<h1 style="color:white" class="mui-title">Contact Us</h1>
			</header>
			<div class="mui-content" style="text-align:left;padding:10px;overflow-y:auto">
					<div style="text-align:center;margin-top:20vh">
						<!-- Contacts -->
						<div><h2>Contact Us</h2></div>
						<ul>
							<li>
								<dl>
									<dd id="_email3" itemprop="email" style="margin-top:10px;" class="contact-details-margin">
										<i class="fa fa-envelope" style="margin-right:10px;"></i><a href="mailto:wiicleanerteam@gmail.com">wiicleanerteam@gmail.com</a>
									</dd>
								</dl>
							</li>
							<li>
								<dl>
									<dd id="_telephone2" class="contact-details-margin" style="margin-top:10px;">
										<i class="fa fa-phone" style="margin-right:10px;"></i><a href="tel:7787755505" target="_blank">778-775-5505</a>
									</dd>
								</dl>
							</li>
						</ul>
						<!-- End Contacts -->

						<!-- Business Hours -->
						<div class="headline"><h2>Office Time</h2></div>
						<span >
						<span>
							<ul class="list-unstyled margin-bottom-30">
								<li>Mon-Fri: 8am-8pm</li>
							</ul>
						</span>
						</span>
						<!-- End Business Hours -->
					</div>
			</div>
    </mt-popup>
		<div class="mui-content">
			<ul class="mui-table-view mui-table-view-chevron">
				<li class="mui-table-view-cell mui-media">
					<router-link :to="{ name: 'UserSetting', params: { user: user}}"  class="mui-navigate-right">
						<img v-if="user" style="width:42px;height:42px;border-radius:100%" class="mui-media-object mui-pull-left head-img" id="head-img" :src="user.avatar==null? url() :  user.avatar">
						<div v-if="user" class="mui-media-body">
							{{user.name}}
							<p class='mui-ellipsis'>Phone:{{user.phone}}</p>
						</div>
					</router-link>
				</li>
			</ul>
      <div id="tabbar-with-map" class=""  style="margin-top: 25px;">
				
				<ul class="mui-table-view">
					<li class="mui-table-view-cell">
						<router-link :to="{ name: 'CleanerReview', params: { cleaner: user}}" class="mui-navigate-right">
							My Reviews
						</router-link>
					</li>
					<!-- <li class="mui-table-view-cell">
						<a class="mui-navigate-right">
							My Income
						</a>
					</li> -->
					<!-- <li class="mui-table-view-cell">
						<a class="mui-navigate-right">
							Referal
						</a>
					</li> -->
				</ul>
				<ul class="mui-table-view" style="margin-top: 25px;">
					<li class="mui-table-view-cell" @click="aboutUs = true">
						<a class="mui-navigate-right">
							About Wii
						</a>
					</li>
					<li class="mui-table-view-cell" @click=" ToS = true">
						<a class="mui-navigate-right">
							Terms of Service
						</a>
					</li>
					<li class="mui-table-view-cell" @click=" FAQ = true">
						<a class="mui-navigate-right">
							FAQ
						</a>
					</li>
					<li class="mui-table-view-cell" @click=" contactUs = true">
						<a class="mui-navigate-right">
							Contact Us
						</a>
					</li>

				</ul>
				<ul class="mui-table-view" style="margin-top: 25px;">
					<li class="mui-table-view-cell">
						<a style="text-align: center;color: #FF3B30;"  href="#" @click="logout">
							Log Out
						</a>
					</li>
				</ul>
			</div>
		</div>

	</body>
</template>

<script>
import firebase from "firebase";
import axios from "axios";
var count = 0;
export default {
  name: "setting",
  data() {
    return {
      busy: false,
      data: [],
      page: 0,
      loading: true,
      user: null,
      aboutUs: false,
      contactUs: false,
      ToS: false,
      FAQ: false
    };
  },
  created() {
    this.user = JSON.parse(localStorage.getItem("user"));
  },
  methods: {
    logout: function() {
      firebase
        .auth()
        .signOut()
        .then(() => {
          mui.toast("Logging Out Successfully!");
          localStorage.removeItem("access_token");
          localStorage.removeItem("user");
          this.$router.replace("login");
        });
    },
    redirect: function() {
      this.$router.replace("hello");
    },
    loadMore: function() {
      this.busy = true;

      setTimeout(() => {
        axios
          .post(
            "http://foreclean.tk:8000/zhidao/tech/getFinishList",
            JSON.stringify({})
          )
          .then(response => {
            console.log(response);
            if (response.data.success == true) {
              this.page++;
              this.data = this.data.concat(response.data.orders);
              if (response.data.orders.length < 10) {
                this.busy = true;
                this.loading = false;
              } else {
                this.busy = false;
              }
            } else {
              mui.toast("数据获取失败");
            }
          })
          .catch(error => {
            console.log(error.response);
          });
      }, 0);
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="less" scoped>
.mui-content {
  padding-top: 0px;
}
.mint-popup-3 {
  width: 100%;
  height: 100%;
  background-color: #fff;
	header{
		z-index: 3000;
	}
  .mui-content {
		margin-top: 44px !important;
		height: 100vh;
  }
}

.mint-popup-3 .mint-button {
  position: absolute;
  width: 90%;
  top: 50%;
  left: 5%;
  transform: translateY(-50%);
}
</style>
